{{- range .Values.imageCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .name | quote }}
data:
  .dockerconfigjson: {{" "}} {{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .registry (printf "%s:%s" .username .password | b64enc) | b64enc }}
type: kubernetes.io/dockerconfigjson
---
{{- end }}

---
