name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot-url
  HELM_CHART_PATH: ./helmchart/telegram-bot-url

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: make build

      - name: Test
        run: make test

  post-build:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ['docker', 'helm']
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: matrix.task == 'docker'
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        if: matrix.task == 'docker'
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Set up Helm
        uses: azure/setup-helm@v1
        if: matrix.task == 'helm'
        with:
          version: 'v3.4.0'

      - name: Lint Helm chart
        run: helm lint ${{ env.HELM_CHART_PATH }}
        if: matrix.task == 'helm'